"use client";

export default function Error({ error, reset }: { error: Error; reset: () => void }) {
  return (
    <div className="rounded-xl border border-[var(--color-decline)]/40 bg-[var(--color-decline)]/5 p-6">
      <h2 className="text-sm font-semibold">This page could not load</h2>
      <p className="mt-2 text-sm text-[var(--text-muted)]">{error.message}</p>
      <p className="mt-2 text-xs text-[var(--text-muted)]">
        Demo snapshots are generated by <code>make demo-data</code>.
      </p>
      <button
        type="button"
        onClick={reset}
        className="mt-4 rounded-md border border-[var(--border)] px-3 py-1.5 text-xs"
      >
        Try again
      </button>
    </div>
  );
}
